/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_reclamation (void)
{
  GtkWidget *espace_reclamation;
  GtkWidget *alignment1;
  GtkWidget *fixed1;
  GtkWidget *mentry_ajout_user;
  GtkWidget *mentry_ajout_rec;
  GtkWidget *mentry_ajout_id;
  GtkWidget *calendar1;
  GtkWidget *image37;
  GtkWidget *image39;
  GtkWidget *image40;
  GtkWidget *mlabel_ajout_service;
  GtkWidget *mlabel_ajout_user;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *mlabel21_note;
  GtkWidget *mlabel_ajout_id;
  GtkWidget *wlabel_ajout_rec;
  GtkWidget *mbutton_espacerec_back;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image29;
  GtkWidget *label12;
  GtkWidget *mlabel_ajout_date;
  GtkWidget *labelm_deg;
  GtkWidget *image42;
  GtkWidget *image38;
  GtkWidget *mbutton_ajout_valid;
  GtkWidget *alignment18;
  GtkWidget *hbox16;
  GtkWidget *image41;
  GtkWidget *label22;
  GtkWidget *radiobutton_ajout_heber;
  GSList *radiobutton_ajout_heber_group = NULL;
  GtkWidget *mcomboboxentry_urgence;
  GtkWidget *radiobutton_ajout_resto;
  GtkWidget *checkbutton1;
  GtkWidget *labelm_user;
  GtkWidget *labelm_rec;
  GtkWidget *label_titre;
  GtkWidget *labelm_id;

  espace_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_reclamation), _("espace_reclamation"));
  gtk_window_set_modal (GTK_WINDOW (espace_reclamation), TRUE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (espace_reclamation), alignment1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed1);

  mentry_ajout_user = gtk_entry_new ();
  gtk_widget_show (mentry_ajout_user);
  gtk_fixed_put (GTK_FIXED (fixed1), mentry_ajout_user, 264, 160);
  gtk_widget_set_size_request (mentry_ajout_user, 200, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_ajout_user), 8226);

  mentry_ajout_rec = gtk_entry_new ();
  gtk_widget_show (mentry_ajout_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), mentry_ajout_rec, 88, 496);
  gtk_widget_set_size_request (mentry_ajout_rec, 528, 160);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_ajout_rec), 8226);

  mentry_ajout_id = gtk_entry_new ();
  gtk_widget_show (mentry_ajout_id);
  gtk_fixed_put (GTK_FIXED (fixed1), mentry_ajout_id, 264, 200);
  gtk_widget_set_size_request (mentry_ajout_id, 200, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_ajout_id), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed1), calendar1, 632, 416);
  gtk_widget_set_size_request (calendar1, 320, 240);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  image37 = create_pixmap (espace_reclamation, "Capture-removebg-preview.png");
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed1), image37, 808, 0);
  gtk_widget_set_size_request (image37, 205, 96);

  image39 = create_pixmap (espace_reclamation, "restaurant.png");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed1), image39, 368, 264);
  gtk_widget_set_size_request (image39, 32, 24);

  image40 = create_pixmap (espace_reclamation, "home(1).png");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed1), image40, 368, 296);
  gtk_widget_set_size_request (image40, 32, 24);

  mlabel_ajout_service = gtk_label_new (_("type de reclamation :"));
  gtk_widget_show (mlabel_ajout_service);
  gtk_fixed_put (GTK_FIXED (fixed1), mlabel_ajout_service, 56, 264);
  gtk_widget_set_size_request (mlabel_ajout_service, 197, 26);

  mlabel_ajout_user = gtk_label_new (_("Nom de l'utilisateur : "));
  gtk_widget_show (mlabel_ajout_user);
  gtk_fixed_put (GTK_FIXED (fixed1), mlabel_ajout_user, 32, 152);
  gtk_widget_set_size_request (mlabel_ajout_user, 264, 40);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 20, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 240, 368);
  gtk_widget_set_size_request (spinbutton1, 128, 24);

  mlabel21_note = gtk_label_new (_("note du service:"));
  gtk_widget_show (mlabel21_note);
  gtk_fixed_put (GTK_FIXED (fixed1), mlabel21_note, 72, 368);
  gtk_widget_set_size_request (mlabel21_note, 192, 32);

  mlabel_ajout_id = gtk_label_new (_(" ID reclamation :"));
  gtk_widget_show (mlabel_ajout_id);
  gtk_fixed_put (GTK_FIXED (fixed1), mlabel_ajout_id, 56, 200);
  gtk_widget_set_size_request (mlabel_ajout_id, 240, 24);

  wlabel_ajout_rec = gtk_label_new (_("saisir votre reclamation :"));
  gtk_widget_show (wlabel_ajout_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), wlabel_ajout_rec, 32, 456);
  gtk_widget_set_size_request (wlabel_ajout_rec, 211, 23);

  mbutton_espacerec_back = gtk_button_new ();
  gtk_widget_show (mbutton_espacerec_back);
  gtk_fixed_put (GTK_FIXED (fixed1), mbutton_espacerec_back, 248, 768);
  gtk_widget_set_size_request (mbutton_espacerec_back, 224, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (mbutton_espacerec_back), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox10), image29, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox10), label12, FALSE, FALSE, 0);

  mlabel_ajout_date = gtk_label_new (_("Date de reclamation :"));
  gtk_widget_show (mlabel_ajout_date);
  gtk_fixed_put (GTK_FIXED (fixed1), mlabel_ajout_date, 680, 384);
  gtk_widget_set_size_request (mlabel_ajout_date, 223, 31);

  labelm_deg = gtk_label_new (_("Degree d'urgence:"));
  gtk_widget_show (labelm_deg);
  gtk_fixed_put (GTK_FIXED (fixed1), labelm_deg, 680, 216);
  gtk_widget_set_size_request (labelm_deg, 144, 32);

  image42 = create_pixmap (espace_reclamation, "report.png");
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed1), image42, 192, 424);
  gtk_widget_set_size_request (image42, 85, 93);

  image38 = create_pixmap (espace_reclamation, "esprit-removebg-preview.png");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed1), image38, 0, 0);
  gtk_widget_set_size_request (image38, 304, 112);

  mbutton_ajout_valid = gtk_button_new ();
  gtk_widget_show (mbutton_ajout_valid);
  gtk_fixed_put (GTK_FIXED (fixed1), mbutton_ajout_valid, 536, 768);
  gtk_widget_set_size_request (mbutton_ajout_valid, 216, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (mbutton_ajout_valid), alignment18);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox16);

  image41 = create_pixmap (espace_reclamation, "plus(2).png");
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox16), image41, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox16), label22, FALSE, FALSE, 0);

  radiobutton_ajout_heber = gtk_radio_button_new_with_mnemonic (NULL, _("h\303\251bergement"));
  gtk_widget_show (radiobutton_ajout_heber);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton_ajout_heber, 240, 296);
  gtk_widget_set_size_request (radiobutton_ajout_heber, 126, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_ajout_heber), radiobutton_ajout_heber_group);
  radiobutton_ajout_heber_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_ajout_heber));

  mcomboboxentry_urgence = gtk_combo_box_entry_new_text ();
  gtk_widget_show (mcomboboxentry_urgence);
  gtk_fixed_put (GTK_FIXED (fixed1), mcomboboxentry_urgence, 632, 256);
  gtk_widget_set_size_request (mcomboboxentry_urgence, 255, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mcomboboxentry_urgence), _("tres_urgent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mcomboboxentry_urgence), _("pas_vraiment"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mcomboboxentry_urgence), _("cest_pas_urgent"));

  radiobutton_ajout_resto = gtk_radio_button_new_with_mnemonic (NULL, _("r\303\251stauration"));
  gtk_widget_show (radiobutton_ajout_resto);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton_ajout_resto, 240, 264);
  gtk_widget_set_size_request (radiobutton_ajout_resto, 126, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_ajout_resto), radiobutton_ajout_heber_group);
  radiobutton_ajout_heber_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_ajout_resto));

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("vous etes sur de votre reclamation"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 64, 696);
  gtk_widget_set_size_request (checkbutton1, 288, 16);

  labelm_user = gtk_label_new ("");
  gtk_widget_show (labelm_user);
  gtk_fixed_put (GTK_FIXED (fixed1), labelm_user, 504, 144);
  gtk_widget_set_size_request (labelm_user, 368, 32);

  labelm_rec = gtk_label_new ("");
  gtk_widget_show (labelm_rec);
  gtk_fixed_put (GTK_FIXED (fixed1), labelm_rec, 440, 320);
  gtk_widget_set_size_request (labelm_rec, 416, 32);

  label_titre = gtk_label_new (_("<span foreground='red'  size='30000' weight='bold'  style='ITALIC'\nfont_family='times'\n   > Espace r\303\251clamations</span>"));
  gtk_widget_show (label_titre);
  gtk_fixed_put (GTK_FIXED (fixed1), label_titre, 272, 40);
  gtk_widget_set_size_request (label_titre, 488, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_titre), TRUE);

  labelm_id = gtk_label_new ("");
  gtk_widget_show (labelm_id);
  gtk_fixed_put (GTK_FIXED (fixed1), labelm_id, 504, 184);
  gtk_widget_set_size_request (labelm_id, 288, 40);

  g_signal_connect ((gpointer) mbutton_espacerec_back, "clicked",
                    G_CALLBACK (on_wbutton_espacerec_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) mbutton_ajout_valid, "clicked",
                    G_CALLBACK (on_wbutton_ajout_valid_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_ajout_heber, "toggled",
                    G_CALLBACK (on_radiobutton_ajout_heber_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_ajout_resto, "toggled",
                    G_CALLBACK (on_radiobutton_ajout_resto_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_reclamation, espace_reclamation, "espace_reclamation");
  GLADE_HOOKUP_OBJECT (espace_reclamation, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espace_reclamation, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mentry_ajout_user, "mentry_ajout_user");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mentry_ajout_rec, "mentry_ajout_rec");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mentry_ajout_id, "mentry_ajout_id");
  GLADE_HOOKUP_OBJECT (espace_reclamation, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image37, "image37");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image39, "image39");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image40, "image40");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mlabel_ajout_service, "mlabel_ajout_service");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mlabel_ajout_user, "mlabel_ajout_user");
  GLADE_HOOKUP_OBJECT (espace_reclamation, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mlabel21_note, "mlabel21_note");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mlabel_ajout_id, "mlabel_ajout_id");
  GLADE_HOOKUP_OBJECT (espace_reclamation, wlabel_ajout_rec, "wlabel_ajout_rec");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mbutton_espacerec_back, "mbutton_espacerec_back");
  GLADE_HOOKUP_OBJECT (espace_reclamation, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (espace_reclamation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image29, "image29");
  GLADE_HOOKUP_OBJECT (espace_reclamation, label12, "label12");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mlabel_ajout_date, "mlabel_ajout_date");
  GLADE_HOOKUP_OBJECT (espace_reclamation, labelm_deg, "labelm_deg");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image42, "image42");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image38, "image38");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mbutton_ajout_valid, "mbutton_ajout_valid");
  GLADE_HOOKUP_OBJECT (espace_reclamation, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (espace_reclamation, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (espace_reclamation, image41, "image41");
  GLADE_HOOKUP_OBJECT (espace_reclamation, label22, "label22");
  GLADE_HOOKUP_OBJECT (espace_reclamation, radiobutton_ajout_heber, "radiobutton_ajout_heber");
  GLADE_HOOKUP_OBJECT (espace_reclamation, mcomboboxentry_urgence, "mcomboboxentry_urgence");
  GLADE_HOOKUP_OBJECT (espace_reclamation, radiobutton_ajout_resto, "radiobutton_ajout_resto");
  GLADE_HOOKUP_OBJECT (espace_reclamation, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (espace_reclamation, labelm_user, "labelm_user");
  GLADE_HOOKUP_OBJECT (espace_reclamation, labelm_rec, "labelm_rec");
  GLADE_HOOKUP_OBJECT (espace_reclamation, label_titre, "label_titre");
  GLADE_HOOKUP_OBJECT (espace_reclamation, labelm_id, "labelm_id");

  return espace_reclamation;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed3;
  GtkWidget *mentry_suppr_id;
  GtkWidget *mlabel_suppr_id;
  GtkWidget *label_titre_spr;
  GtkWidget *image45;
  GtkWidget *image46;
  GtkWidget *checkbutton2;
  GtkWidget *labelmessage;
  GtkWidget *mbutton_suppr_valid;
  GtkWidget *alignment19;
  GtkWidget *hbox17;
  GtkWidget *image43;
  GtkWidget *label23;
  GtkWidget *mbutton_suppr_back;
  GtkWidget *alignment20;
  GtkWidget *hbox18;
  GtkWidget *image44;
  GtkWidget *label24;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed3);

  mentry_suppr_id = gtk_entry_new ();
  gtk_widget_show (mentry_suppr_id);
  gtk_fixed_put (GTK_FIXED (fixed3), mentry_suppr_id, 296, 112);
  gtk_widget_set_size_request (mentry_suppr_id, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_suppr_id), 8226);

  mlabel_suppr_id = gtk_label_new (_("ID reclamation"));
  gtk_widget_show (mlabel_suppr_id);
  gtk_fixed_put (GTK_FIXED (fixed3), mlabel_suppr_id, 120, 112);
  gtk_widget_set_size_request (mlabel_suppr_id, 176, 32);

  label_titre_spr = gtk_label_new (_("<span foreground='red'  size='30000' weight='bold'  style='ITALIC'\nfont_family='times'\n   >supprimer r\303\251clamation</span>"));
  gtk_widget_show (label_titre_spr);
  gtk_fixed_put (GTK_FIXED (fixed3), label_titre_spr, 192, 16);
  gtk_widget_set_size_request (label_titre_spr, 448, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_titre_spr), TRUE);

  image45 = create_pixmap (supprimer, "Capture-removebg-preview.png");
  gtk_widget_show (image45);
  gtk_fixed_put (GTK_FIXED (fixed3), image45, 608, 0);
  gtk_widget_set_size_request (image45, 205, 72);

  image46 = create_pixmap (supprimer, "esprit-removebg-preview.png");
  gtk_widget_show (image46);
  gtk_fixed_put (GTK_FIXED (fixed3), image46, 0, 0);
  gtk_widget_set_size_request (image46, 312, 120);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("supprimer la reclamation "));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 216, 200);
  gtk_widget_set_size_request (checkbutton2, 384, 24);

  labelmessage = gtk_label_new ("");
  gtk_widget_show (labelmessage);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmessage, 216, 160);
  gtk_widget_set_size_request (labelmessage, 289, 33);

  mbutton_suppr_valid = gtk_button_new ();
  gtk_widget_show (mbutton_suppr_valid);
  gtk_fixed_put (GTK_FIXED (fixed3), mbutton_suppr_valid, 384, 240);
  gtk_widget_set_size_request (mbutton_suppr_valid, 208, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (mbutton_suppr_valid), alignment19);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox17);

  image43 = create_pixmap (supprimer, "delete.png");
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox17), image43, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox17), label23, FALSE, FALSE, 0);

  mbutton_suppr_back = gtk_button_new ();
  gtk_widget_show (mbutton_suppr_back);
  gtk_fixed_put (GTK_FIXED (fixed3), mbutton_suppr_back, 136, 240);
  gtk_widget_set_size_request (mbutton_suppr_back, 216, 37);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (mbutton_suppr_back), alignment20);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox18);

  image44 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox18), image44, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox18), label24, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) mbutton_suppr_valid, "clicked",
                    G_CALLBACK (on_wbutton_suppr_valid_clicked),
                    NULL);
  g_signal_connect ((gpointer) mbutton_suppr_back, "clicked",
                    G_CALLBACK (on_wbutton_suppr_back_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (supprimer, mentry_suppr_id, "mentry_suppr_id");
  GLADE_HOOKUP_OBJECT (supprimer, mlabel_suppr_id, "mlabel_suppr_id");
  GLADE_HOOKUP_OBJECT (supprimer, label_titre_spr, "label_titre_spr");
  GLADE_HOOKUP_OBJECT (supprimer, image45, "image45");
  GLADE_HOOKUP_OBJECT (supprimer, image46, "image46");
  GLADE_HOOKUP_OBJECT (supprimer, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (supprimer, labelmessage, "labelmessage");
  GLADE_HOOKUP_OBJECT (supprimer, mbutton_suppr_valid, "mbutton_suppr_valid");
  GLADE_HOOKUP_OBJECT (supprimer, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (supprimer, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (supprimer, image43, "image43");
  GLADE_HOOKUP_OBJECT (supprimer, label23, "label23");
  GLADE_HOOKUP_OBJECT (supprimer, mbutton_suppr_back, "mbutton_suppr_back");
  GLADE_HOOKUP_OBJECT (supprimer, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (supprimer, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (supprimer, image44, "image44");
  GLADE_HOOKUP_OBJECT (supprimer, label24, "label24");

  return supprimer;
}

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *label_titre_acc;
  GtkWidget *image47;
  GtkWidget *image48;
  GtkWidget *label25;
  GtkWidget *button_acc_modifier;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image20;
  GtkWidget *label5;
  GtkWidget *button_acc_supprim;
  GtkWidget *alignment4;
  GtkWidget *hbox3;
  GtkWidget *image19;
  GtkWidget *label4;
  GtkWidget *button_acc_actu;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image22;
  GtkWidget *label7;
  GtkWidget *button_acc_decnx;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image17;
  GtkWidget *label2;
  GtkWidget *button_acc_recherche;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image21;
  GtkWidget *label6;
  GtkWidget *button_acc_ajoutm;
  GtkWidget *alignment3;
  GtkWidget *hbox2;
  GtkWidget *image18;
  GtkWidget *label3;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed6);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow1, 144, 160);
  gtk_widget_set_size_request (scrolledwindow1, 632, 440);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 432, 336);

  label_titre_acc = gtk_label_new (_("<span foreground='red'  size='30000' weight='bold'  style='ITALIC'\nfont_family='times'\n   >Gestion des r\303\251clamations</span>"));
  gtk_widget_show (label_titre_acc);
  gtk_fixed_put (GTK_FIXED (fixed6), label_titre_acc, 240, 24);
  gtk_widget_set_size_request (label_titre_acc, 432, 64);
  gtk_label_set_use_markup (GTK_LABEL (label_titre_acc), TRUE);

  image47 = create_pixmap (acceuil, "Capture-removebg-preview.png");
  gtk_widget_show (image47);
  gtk_fixed_put (GTK_FIXED (fixed6), image47, 720, 0);
  gtk_widget_set_size_request (image47, 205, 96);

  image48 = create_pixmap (acceuil, "esprit-removebg-preview.png");
  gtk_widget_show (image48);
  gtk_fixed_put (GTK_FIXED (fixed6), image48, 0, 0);
  gtk_widget_set_size_request (image48, 288, 144);

  label25 = gtk_label_new (_("Les r\303\251clamations:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 0, 104);
  gtk_widget_set_size_request (label25, 288, 80);

  button_acc_modifier = gtk_button_new ();
  gtk_widget_show (button_acc_modifier);
  gtk_fixed_put (GTK_FIXED (fixed6), button_acc_modifier, 168, 712);
  gtk_widget_set_size_request (button_acc_modifier, 216, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_acc_modifier), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image20 = create_pixmap (acceuil, "edit(4).png");
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox4), image20, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button_acc_supprim = gtk_button_new ();
  gtk_widget_show (button_acc_supprim);
  gtk_fixed_put (GTK_FIXED (fixed6), button_acc_supprim, 456, 656);
  gtk_widget_set_size_request (button_acc_supprim, 224, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_acc_supprim), alignment4);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox3);

  image19 = create_pixmap (acceuil, "delete.png");
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox3), image19, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button_acc_actu = gtk_button_new ();
  gtk_widget_show (button_acc_actu);
  gtk_fixed_put (GTK_FIXED (fixed6), button_acc_actu, 16, 800);
  gtk_widget_set_size_request (button_acc_actu, 120, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_acc_actu), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image22 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox6), image22, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("actualiser "));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  button_acc_decnx = gtk_button_new ();
  gtk_widget_show (button_acc_decnx);
  gtk_fixed_put (GTK_FIXED (fixed6), button_acc_decnx, 784, 800);
  gtk_widget_set_size_request (button_acc_decnx, 120, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_acc_decnx), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image17 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox1), image17, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("deconnexion"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  button_acc_recherche = gtk_button_new ();
  gtk_widget_show (button_acc_recherche);
  gtk_fixed_put (GTK_FIXED (fixed6), button_acc_recherche, 408, 712);
  gtk_widget_set_size_request (button_acc_recherche, 184, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_acc_recherche), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image21 = create_pixmap (acceuil, "search.png");
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox5), image21, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  button_acc_ajoutm = gtk_button_new ();
  gtk_widget_show (button_acc_ajoutm);
  gtk_fixed_put (GTK_FIXED (fixed6), button_acc_ajoutm, 232, 656);
  gtk_widget_set_size_request (button_acc_ajoutm, 208, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_acc_ajoutm), alignment3);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox2);

  image18 = create_pixmap (acceuil, "plus(2).png");
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox2), image18, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_acc_modifier, "clicked",
                    G_CALLBACK (on_button_acc_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acc_supprim, "clicked",
                    G_CALLBACK (on_button_acc_supprim_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acc_actu, "clicked",
                    G_CALLBACK (on_button_acc_actu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acc_decnx, "clicked",
                    G_CALLBACK (on_button_acc_decnx_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acc_recherche, "clicked",
                    G_CALLBACK (on_button_acc_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_acc_ajoutm, "clicked",
                    G_CALLBACK (on_button_acc_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (acceuil, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (acceuil, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (acceuil, label_titre_acc, "label_titre_acc");
  GLADE_HOOKUP_OBJECT (acceuil, image47, "image47");
  GLADE_HOOKUP_OBJECT (acceuil, image48, "image48");
  GLADE_HOOKUP_OBJECT (acceuil, label25, "label25");
  GLADE_HOOKUP_OBJECT (acceuil, button_acc_modifier, "button_acc_modifier");
  GLADE_HOOKUP_OBJECT (acceuil, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (acceuil, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (acceuil, image20, "image20");
  GLADE_HOOKUP_OBJECT (acceuil, label5, "label5");
  GLADE_HOOKUP_OBJECT (acceuil, button_acc_supprim, "button_acc_supprim");
  GLADE_HOOKUP_OBJECT (acceuil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (acceuil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (acceuil, image19, "image19");
  GLADE_HOOKUP_OBJECT (acceuil, label4, "label4");
  GLADE_HOOKUP_OBJECT (acceuil, button_acc_actu, "button_acc_actu");
  GLADE_HOOKUP_OBJECT (acceuil, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (acceuil, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (acceuil, image22, "image22");
  GLADE_HOOKUP_OBJECT (acceuil, label7, "label7");
  GLADE_HOOKUP_OBJECT (acceuil, button_acc_decnx, "button_acc_decnx");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image17, "image17");
  GLADE_HOOKUP_OBJECT (acceuil, label2, "label2");
  GLADE_HOOKUP_OBJECT (acceuil, button_acc_recherche, "button_acc_recherche");
  GLADE_HOOKUP_OBJECT (acceuil, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (acceuil, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (acceuil, image21, "image21");
  GLADE_HOOKUP_OBJECT (acceuil, label6, "label6");
  GLADE_HOOKUP_OBJECT (acceuil, button_acc_ajoutm, "button_acc_ajoutm");
  GLADE_HOOKUP_OBJECT (acceuil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image18, "image18");
  GLADE_HOOKUP_OBJECT (acceuil, label3, "label3");

  return acceuil;
}

GtkWidget*
create_modifier_rec (void)
{
  GtkWidget *modifier_rec;
  GtkWidget *fixed7;
  GtkWidget *mentry_modif_id;
  GtkWidget *mentry_modif_user;
  GtkWidget *mentry_modif_rec;
  GtkObject *spinbutton_modif_jour_adj;
  GtkWidget *spinbutton_modif_jour;
  GtkObject *spinbutton_modif_mois_adj;
  GtkWidget *spinbutton_modif_mois;
  GtkObject *spinbutton_modif_ann_adj;
  GtkWidget *spinbutton_modif_ann;
  GtkWidget *labelm_valid;
  GtkWidget *radiobutton_modif_resto;
  GSList *radiobutton_modif_resto_group = NULL;
  GtkWidget *radiobutton_modif_heber;
  GtkWidget *labelm_modif;
  GtkWidget *label_titre_modif;
  GtkWidget *image49;
  GtkWidget *image50;
  GtkWidget *wlabel_modif_date;
  GtkWidget *mlabel_modif_service;
  GtkWidget *mlabel_niv;
  GtkWidget *wlabel_modif_saisie;
  GtkWidget *wbutton_modifier_back;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image28;
  GtkWidget *label11;
  GtkWidget *checkbuttonmodif;
  GtkWidget *wbutton_modif_valid;
  GtkWidget *alignment21;
  GtkWidget *hbox19;
  GtkWidget *image51;
  GtkWidget *label26;
  GtkWidget *wbutton_consulter;
  GtkWidget *wlabel_modif_user;
  GtkWidget *mlabel_modif_id;
  GtkWidget *wcomboboxentry_niveaum;
  GtkObject *mz_spinbutton2_adj;
  GtkWidget *mz_spinbutton2;
  GtkWidget *mz_label50;

  modifier_rec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_rec), _("modifier_rec"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (modifier_rec), fixed7);

  mentry_modif_id = gtk_entry_new ();
  gtk_widget_show (mentry_modif_id);
  gtk_fixed_put (GTK_FIXED (fixed7), mentry_modif_id, 256, 160);
  gtk_widget_set_size_request (mentry_modif_id, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_modif_id), 8226);

  mentry_modif_user = gtk_entry_new ();
  gtk_widget_show (mentry_modif_user);
  gtk_fixed_put (GTK_FIXED (fixed7), mentry_modif_user, 256, 216);
  gtk_widget_set_size_request (mentry_modif_user, 240, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_modif_user), 8226);

  mentry_modif_rec = gtk_entry_new ();
  gtk_widget_show (mentry_modif_rec);
  gtk_fixed_put (GTK_FIXED (fixed7), mentry_modif_rec, 128, 504);
  gtk_widget_set_size_request (mentry_modif_rec, 488, 128);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_modif_rec), 8226);

  spinbutton_modif_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_modif_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_modif_jour_adj), 1, 0);
  gtk_widget_show (spinbutton_modif_jour);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_modif_jour, 256, 272);
  gtk_widget_set_size_request (spinbutton_modif_jour, 60, 27);

  spinbutton_modif_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_modif_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_modif_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_modif_mois);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_modif_mois, 360, 272);
  gtk_widget_set_size_request (spinbutton_modif_mois, 60, 27);

  spinbutton_modif_ann_adj = gtk_adjustment_new (2020, 1000, 2100, 1, 10, 10);
  spinbutton_modif_ann = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_modif_ann_adj), 1, 0);
  gtk_widget_show (spinbutton_modif_ann);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_modif_ann, 472, 272);
  gtk_widget_set_size_request (spinbutton_modif_ann, 60, 27);

  labelm_valid = gtk_label_new ("");
  gtk_widget_show (labelm_valid);
  gtk_fixed_put (GTK_FIXED (fixed7), labelm_valid, 168, 592);
  gtk_widget_set_size_request (labelm_valid, 350, 48);

  radiobutton_modif_resto = gtk_radio_button_new_with_mnemonic (NULL, _("restauration"));
  gtk_widget_show (radiobutton_modif_resto);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton_modif_resto, 256, 336);
  gtk_widget_set_size_request (radiobutton_modif_resto, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modif_resto), radiobutton_modif_resto_group);
  radiobutton_modif_resto_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modif_resto));

  radiobutton_modif_heber = gtk_radio_button_new_with_mnemonic (NULL, _("hebergement"));
  gtk_widget_show (radiobutton_modif_heber);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton_modif_heber, 456, 336);
  gtk_widget_set_size_request (radiobutton_modif_heber, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modif_heber), radiobutton_modif_resto_group);
  radiobutton_modif_resto_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modif_heber));

  labelm_modif = gtk_label_new ("");
  gtk_widget_show (labelm_modif);
  gtk_fixed_put (GTK_FIXED (fixed7), labelm_modif, 160, 680);
  gtk_widget_set_size_request (labelm_modif, 384, 40);

  label_titre_modif = gtk_label_new (_("<span foreground='red'  size='30000' weight='bold'  style='ITALIC'\nfont_family='times'\n   >Modifier r\303\251clamations</span>"));
  gtk_widget_show (label_titre_modif);
  gtk_fixed_put (GTK_FIXED (fixed7), label_titre_modif, 248, 48);
  gtk_widget_set_size_request (label_titre_modif, 440, 72);
  gtk_label_set_use_markup (GTK_LABEL (label_titre_modif), TRUE);

  image49 = create_pixmap (modifier_rec, "Capture-removebg-preview.png");
  gtk_widget_show (image49);
  gtk_fixed_put (GTK_FIXED (fixed7), image49, 704, 0);
  gtk_widget_set_size_request (image49, 208, 88);

  image50 = create_pixmap (modifier_rec, "esprit-removebg-preview.png");
  gtk_widget_show (image50);
  gtk_fixed_put (GTK_FIXED (fixed7), image50, 0, 0);
  gtk_widget_set_size_request (image50, 304, 128);

  wlabel_modif_date = gtk_label_new (_("la date de votre reclamation"));
  gtk_widget_show (wlabel_modif_date);
  gtk_fixed_put (GTK_FIXED (fixed7), wlabel_modif_date, 40, 272);
  gtk_widget_set_size_request (wlabel_modif_date, 208, 32);

  mlabel_modif_service = gtk_label_new (_("Type de reclamation:"));
  gtk_widget_show (mlabel_modif_service);
  gtk_fixed_put (GTK_FIXED (fixed7), mlabel_modif_service, 24, 336);
  gtk_widget_set_size_request (mlabel_modif_service, 184, 24);

  mlabel_niv = gtk_label_new (_("degre d'urgence :"));
  gtk_widget_show (mlabel_niv);
  gtk_fixed_put (GTK_FIXED (fixed7), mlabel_niv, 32, 376);
  gtk_widget_set_size_request (mlabel_niv, 200, 40);

  wlabel_modif_saisie = gtk_label_new (_(" votre reclamation :"));
  gtk_widget_show (wlabel_modif_saisie);
  gtk_fixed_put (GTK_FIXED (fixed7), wlabel_modif_saisie, 24, 480);
  gtk_widget_set_size_request (wlabel_modif_saisie, 232, 16);

  wbutton_modifier_back = gtk_button_new ();
  gtk_widget_show (wbutton_modifier_back);
  gtk_fixed_put (GTK_FIXED (fixed7), wbutton_modifier_back, 16, 784);
  gtk_widget_set_size_request (wbutton_modifier_back, 177, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (wbutton_modifier_back), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image28 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox9), image28, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("revenir a l'acceuil "));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox9), label11, FALSE, FALSE, 0);

  checkbuttonmodif = gtk_check_button_new_with_mnemonic (_("si vous \303\252tes satisfait de votre experience sur cet espace veuillez chocher cette case"));
  gtk_widget_show (checkbuttonmodif);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbuttonmodif, 120, 656);
  gtk_widget_set_size_request (checkbuttonmodif, 584, 32);

  wbutton_modif_valid = gtk_button_new ();
  gtk_widget_show (wbutton_modif_valid);
  gtk_fixed_put (GTK_FIXED (fixed7), wbutton_modif_valid, 584, 752);
  gtk_widget_set_size_request (wbutton_modif_valid, 234, 45);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (wbutton_modif_valid), alignment21);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox19);

  image51 = create_pixmap (modifier_rec, "edit(4).png");
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox19), image51, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("modifier "));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox19), label26, FALSE, FALSE, 0);

  wbutton_consulter = gtk_button_new_with_mnemonic (_("consulter"));
  gtk_widget_show (wbutton_consulter);
  gtk_fixed_put (GTK_FIXED (fixed7), wbutton_consulter, 552, 160);
  gtk_widget_set_size_request (wbutton_consulter, 120, 32);

  wlabel_modif_user = gtk_label_new (_("ID reclamation"));
  gtk_widget_show (wlabel_modif_user);
  gtk_fixed_put (GTK_FIXED (fixed7), wlabel_modif_user, 56, 160);
  gtk_widget_set_size_request (wlabel_modif_user, 176, 32);

  mlabel_modif_id = gtk_label_new (_("Nom de l'utilisateur"));
  gtk_widget_show (mlabel_modif_id);
  gtk_fixed_put (GTK_FIXED (fixed7), mlabel_modif_id, 64, 224);
  gtk_widget_set_size_request (mlabel_modif_id, 176, 24);

  wcomboboxentry_niveaum = gtk_combo_box_entry_new_text ();
  gtk_widget_show (wcomboboxentry_niveaum);
  gtk_fixed_put (GTK_FIXED (fixed7), wcomboboxentry_niveaum, 264, 392);
  gtk_widget_set_size_request (wcomboboxentry_niveaum, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (wcomboboxentry_niveaum), _("tres_urgent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (wcomboboxentry_niveaum), _("pas_vraiment"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (wcomboboxentry_niveaum), _("cest_pas_urgent"));

  mz_spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mz_spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (mz_spinbutton2_adj), 1, 0);
  gtk_widget_show (mz_spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed7), mz_spinbutton2, 640, 392);
  gtk_widget_set_size_request (mz_spinbutton2, 60, 27);

  mz_label50 = gtk_label_new (_("note de service :"));
  gtk_widget_show (mz_label50);
  gtk_fixed_put (GTK_FIXED (fixed7), mz_label50, 480, 392);
  gtk_widget_set_size_request (mz_label50, 136, 32);

  g_signal_connect ((gpointer) wbutton_modifier_back, "clicked",
                    G_CALLBACK (on_wbutton_modifier_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) wbutton_modif_valid, "clicked",
                    G_CALLBACK (on_wbutton_modif_valid_clicked),
                    NULL);
  g_signal_connect ((gpointer) wbutton_consulter, "clicked",
                    G_CALLBACK (on_wbutton_consulter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_rec, modifier_rec, "modifier_rec");
  GLADE_HOOKUP_OBJECT (modifier_rec, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (modifier_rec, mentry_modif_id, "mentry_modif_id");
  GLADE_HOOKUP_OBJECT (modifier_rec, mentry_modif_user, "mentry_modif_user");
  GLADE_HOOKUP_OBJECT (modifier_rec, mentry_modif_rec, "mentry_modif_rec");
  GLADE_HOOKUP_OBJECT (modifier_rec, spinbutton_modif_jour, "spinbutton_modif_jour");
  GLADE_HOOKUP_OBJECT (modifier_rec, spinbutton_modif_mois, "spinbutton_modif_mois");
  GLADE_HOOKUP_OBJECT (modifier_rec, spinbutton_modif_ann, "spinbutton_modif_ann");
  GLADE_HOOKUP_OBJECT (modifier_rec, labelm_valid, "labelm_valid");
  GLADE_HOOKUP_OBJECT (modifier_rec, radiobutton_modif_resto, "radiobutton_modif_resto");
  GLADE_HOOKUP_OBJECT (modifier_rec, radiobutton_modif_heber, "radiobutton_modif_heber");
  GLADE_HOOKUP_OBJECT (modifier_rec, labelm_modif, "labelm_modif");
  GLADE_HOOKUP_OBJECT (modifier_rec, label_titre_modif, "label_titre_modif");
  GLADE_HOOKUP_OBJECT (modifier_rec, image49, "image49");
  GLADE_HOOKUP_OBJECT (modifier_rec, image50, "image50");
  GLADE_HOOKUP_OBJECT (modifier_rec, wlabel_modif_date, "wlabel_modif_date");
  GLADE_HOOKUP_OBJECT (modifier_rec, mlabel_modif_service, "mlabel_modif_service");
  GLADE_HOOKUP_OBJECT (modifier_rec, mlabel_niv, "mlabel_niv");
  GLADE_HOOKUP_OBJECT (modifier_rec, wlabel_modif_saisie, "wlabel_modif_saisie");
  GLADE_HOOKUP_OBJECT (modifier_rec, wbutton_modifier_back, "wbutton_modifier_back");
  GLADE_HOOKUP_OBJECT (modifier_rec, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier_rec, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier_rec, image28, "image28");
  GLADE_HOOKUP_OBJECT (modifier_rec, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifier_rec, checkbuttonmodif, "checkbuttonmodif");
  GLADE_HOOKUP_OBJECT (modifier_rec, wbutton_modif_valid, "wbutton_modif_valid");
  GLADE_HOOKUP_OBJECT (modifier_rec, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (modifier_rec, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (modifier_rec, image51, "image51");
  GLADE_HOOKUP_OBJECT (modifier_rec, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifier_rec, wbutton_consulter, "wbutton_consulter");
  GLADE_HOOKUP_OBJECT (modifier_rec, wlabel_modif_user, "wlabel_modif_user");
  GLADE_HOOKUP_OBJECT (modifier_rec, mlabel_modif_id, "mlabel_modif_id");
  GLADE_HOOKUP_OBJECT (modifier_rec, wcomboboxentry_niveaum, "wcomboboxentry_niveaum");
  GLADE_HOOKUP_OBJECT (modifier_rec, mz_spinbutton2, "mz_spinbutton2");
  GLADE_HOOKUP_OBJECT (modifier_rec, mz_label50, "mz_label50");

  return modifier_rec;
}

GtkWidget*
create_rechercher (void)
{
  GtkWidget *rechercher;
  GtkWidget *fixed8;
  GtkWidget *mentry_rechercher_id;
  GtkWidget *treeview2;
  GtkWidget *wlabel_rechercher_id;
  GtkWidget *label_titre_rech;
  GtkWidget *image53;
  GtkWidget *image52;
  GtkWidget *wbutton_recherche_affich;
  GtkWidget *wbutton_rechercher_back;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image26;
  GtkWidget *label9;
  GtkWidget *notebook1;
  GtkWidget *fixed9;
  GtkWidget *wradiobutton_resto_r;
  GSList *wradiobutton_resto_r_group = NULL;
  GtkWidget *wradiobutton_heber_r;
  GtkWidget *alignment17;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview3;
  GtkWidget *wbutton_cherch_serv;
  GtkWidget *alignment14;
  GtkWidget *hbox13;
  GtkWidget *image34;
  GtkWidget *label18;
  GtkWidget *mlabel_type;
  GtkWidget *fixed10;
  GtkWidget *treeview4;
  GtkWidget *wradiobutton_n1;
  GSList *wradiobutton_n1_group = NULL;
  GtkWidget *wradiobutton_n2;
  GtkWidget *wradiobutton_n3;
  GtkWidget *button_cherch_niv;
  GtkWidget *alignment15;
  GtkWidget *hbox14;
  GtkWidget *image35;
  GtkWidget *label19;
  GtkWidget *mlabelr_deg;

  rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rechercher), _("rechercher"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (rechercher), fixed8);

  mentry_rechercher_id = gtk_entry_new ();
  gtk_widget_show (mentry_rechercher_id);
  gtk_fixed_put (GTK_FIXED (fixed8), mentry_rechercher_id, 304, 128);
  gtk_widget_set_size_request (mentry_rechercher_id, 162, 31);
  gtk_entry_set_invisible_char (GTK_ENTRY (mentry_rechercher_id), 8226);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 88, 192);
  gtk_widget_set_size_request (treeview2, 623, 50);

  wlabel_rechercher_id = gtk_label_new (_("ID reclamation"));
  gtk_widget_show (wlabel_rechercher_id);
  gtk_fixed_put (GTK_FIXED (fixed8), wlabel_rechercher_id, 128, 120);
  gtk_widget_set_size_request (wlabel_rechercher_id, 134, 40);

  label_titre_rech = gtk_label_new (_("<span foreground='red'  size='30000' weight='bold'  style='ITALIC'\nfont_family='times'\n   >Chercher votre r\303\251clamations</span>"));
  gtk_widget_show (label_titre_rech);
  gtk_fixed_put (GTK_FIXED (fixed8), label_titre_rech, 192, 32);
  gtk_widget_set_size_request (label_titre_rech, 534, 67);
  gtk_label_set_use_markup (GTK_LABEL (label_titre_rech), TRUE);

  image53 = create_pixmap (rechercher, "esprit-removebg-preview.png");
  gtk_widget_show (image53);
  gtk_fixed_put (GTK_FIXED (fixed8), image53, 0, 0);
  gtk_widget_set_size_request (image53, 312, 144);

  image52 = create_pixmap (rechercher, "Capture-removebg-preview.png");
  gtk_widget_show (image52);
  gtk_fixed_put (GTK_FIXED (fixed8), image52, 712, 0);
  gtk_widget_set_size_request (image52, 205, 96);

  wbutton_recherche_affich = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (wbutton_recherche_affich);
  gtk_fixed_put (GTK_FIXED (fixed8), wbutton_recherche_affich, 512, 128);
  gtk_widget_set_size_request (wbutton_recherche_affich, 136, 32);

  wbutton_rechercher_back = gtk_button_new ();
  gtk_widget_show (wbutton_rechercher_back);
  gtk_fixed_put (GTK_FIXED (fixed8), wbutton_rechercher_back, 328, 576);
  gtk_widget_set_size_request (wbutton_rechercher_back, 151, 35);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (wbutton_rechercher_back), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox7), image26, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("revenir a l'acceuil"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox7), label9, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed8), notebook1, 80, 264);
  gtk_widget_set_size_request (notebook1, 776, 280);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  wradiobutton_resto_r = gtk_radio_button_new_with_mnemonic (NULL, _("restauration"));
  gtk_widget_show (wradiobutton_resto_r);
  gtk_fixed_put (GTK_FIXED (fixed9), wradiobutton_resto_r, 64, 56);
  gtk_widget_set_size_request (wradiobutton_resto_r, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (wradiobutton_resto_r), wradiobutton_resto_r_group);
  wradiobutton_resto_r_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (wradiobutton_resto_r));

  wradiobutton_heber_r = gtk_radio_button_new_with_mnemonic (NULL, _("hebergement"));
  gtk_widget_show (wradiobutton_heber_r);
  gtk_fixed_put (GTK_FIXED (fixed9), wradiobutton_heber_r, 64, 112);
  gtk_widget_set_size_request (wradiobutton_heber_r, 121, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (wradiobutton_heber_r), wradiobutton_resto_r_group);
  wradiobutton_resto_r_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (wradiobutton_heber_r));

  alignment17 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment17);
  gtk_fixed_put (GTK_FIXED (fixed9), alignment17, 256, 24);
  gtk_widget_set_size_request (alignment17, 320, 184);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (alignment17), scrolledwindow2);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview3);
  gtk_widget_set_size_request (treeview3, 308, 209);

  wbutton_cherch_serv = gtk_button_new ();
  gtk_widget_show (wbutton_cherch_serv);
  gtk_fixed_put (GTK_FIXED (fixed9), wbutton_cherch_serv, 32, 168);
  gtk_widget_set_size_request (wbutton_cherch_serv, 146, 41);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (wbutton_cherch_serv), alignment14);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox13);

  image34 = create_pixmap (rechercher, "search.png");
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox13), image34, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox13), label18, FALSE, FALSE, 0);

  mlabel_type = gtk_label_new (_("Type de reclamation"));
  gtk_widget_show (mlabel_type);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), mlabel_type);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview4, 248, 16);
  gtk_widget_set_size_request (treeview4, 496, 184);

  wradiobutton_n1 = gtk_radio_button_new_with_mnemonic (NULL, _("Tr\303\251s urgent"));
  gtk_widget_show (wradiobutton_n1);
  gtk_fixed_put (GTK_FIXED (fixed10), wradiobutton_n1, 48, 32);
  gtk_widget_set_size_request (wradiobutton_n1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (wradiobutton_n1), wradiobutton_n1_group);
  wradiobutton_n1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (wradiobutton_n1));

  wradiobutton_n2 = gtk_radio_button_new_with_mnemonic (NULL, _("pas vraiment"));
  gtk_widget_show (wradiobutton_n2);
  gtk_fixed_put (GTK_FIXED (fixed10), wradiobutton_n2, 48, 72);
  gtk_widget_set_size_request (wradiobutton_n2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (wradiobutton_n2), wradiobutton_n1_group);
  wradiobutton_n1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (wradiobutton_n2));

  wradiobutton_n3 = gtk_radio_button_new_with_mnemonic (NULL, _("c'est pas urgent"));
  gtk_widget_show (wradiobutton_n3);
  gtk_fixed_put (GTK_FIXED (fixed10), wradiobutton_n3, 48, 112);
  gtk_widget_set_size_request (wradiobutton_n3, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (wradiobutton_n3), wradiobutton_n1_group);
  wradiobutton_n1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (wradiobutton_n3));

  button_cherch_niv = gtk_button_new ();
  gtk_widget_show (button_cherch_niv);
  gtk_fixed_put (GTK_FIXED (fixed10), button_cherch_niv, 40, 176);
  gtk_widget_set_size_request (button_cherch_niv, 119, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_cherch_niv), alignment15);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox14);

  image35 = create_pixmap (rechercher, "search.png");
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox14), image35, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox14), label19, FALSE, FALSE, 0);

  mlabelr_deg = gtk_label_new (_("Degre d'urgence"));
  gtk_widget_show (mlabelr_deg);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), mlabelr_deg);
  GTK_WIDGET_SET_FLAGS (mlabelr_deg, GTK_CAN_FOCUS);

  g_signal_connect ((gpointer) wbutton_recherche_affich, "clicked",
                    G_CALLBACK (on_wbutton_recherche_affich_clicked),
                    NULL);
  g_signal_connect ((gpointer) wbutton_rechercher_back, "clicked",
                    G_CALLBACK (on_wbutton_rechercher_back_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) wbutton_cherch_serv, "clicked",
                    G_CALLBACK (on_wbutton_cherch_serv_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview4, "row_activated",
                    G_CALLBACK (on_treeview4_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_cherch_niv, "clicked",
                    G_CALLBACK (on_button_cherch_niv_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechercher, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (rechercher, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (rechercher, mentry_rechercher_id, "mentry_rechercher_id");
  GLADE_HOOKUP_OBJECT (rechercher, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (rechercher, wlabel_rechercher_id, "wlabel_rechercher_id");
  GLADE_HOOKUP_OBJECT (rechercher, label_titre_rech, "label_titre_rech");
  GLADE_HOOKUP_OBJECT (rechercher, image53, "image53");
  GLADE_HOOKUP_OBJECT (rechercher, image52, "image52");
  GLADE_HOOKUP_OBJECT (rechercher, wbutton_recherche_affich, "wbutton_recherche_affich");
  GLADE_HOOKUP_OBJECT (rechercher, wbutton_rechercher_back, "wbutton_rechercher_back");
  GLADE_HOOKUP_OBJECT (rechercher, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (rechercher, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (rechercher, image26, "image26");
  GLADE_HOOKUP_OBJECT (rechercher, label9, "label9");
  GLADE_HOOKUP_OBJECT (rechercher, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (rechercher, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (rechercher, wradiobutton_resto_r, "wradiobutton_resto_r");
  GLADE_HOOKUP_OBJECT (rechercher, wradiobutton_heber_r, "wradiobutton_heber_r");
  GLADE_HOOKUP_OBJECT (rechercher, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (rechercher, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (rechercher, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (rechercher, wbutton_cherch_serv, "wbutton_cherch_serv");
  GLADE_HOOKUP_OBJECT (rechercher, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (rechercher, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (rechercher, image34, "image34");
  GLADE_HOOKUP_OBJECT (rechercher, label18, "label18");
  GLADE_HOOKUP_OBJECT (rechercher, mlabel_type, "mlabel_type");
  GLADE_HOOKUP_OBJECT (rechercher, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (rechercher, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (rechercher, wradiobutton_n1, "wradiobutton_n1");
  GLADE_HOOKUP_OBJECT (rechercher, wradiobutton_n2, "wradiobutton_n2");
  GLADE_HOOKUP_OBJECT (rechercher, wradiobutton_n3, "wradiobutton_n3");
  GLADE_HOOKUP_OBJECT (rechercher, button_cherch_niv, "button_cherch_niv");
  GLADE_HOOKUP_OBJECT (rechercher, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (rechercher, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (rechercher, image35, "image35");
  GLADE_HOOKUP_OBJECT (rechercher, label19, "label19");
  GLADE_HOOKUP_OBJECT (rechercher, mlabelr_deg, "mlabelr_deg");

  return rechercher;
}

