/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_reclamation (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_modifier_rec (void);
GtkWidget* create_rechercher (void);
