/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *espace_reclamation;
  GtkWidget *supprimer;
  GtkWidget *acceuil;
  GtkWidget *modifier_rec;
  GtkWidget *rechercher;
  GtkWidget *treeview1;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (/*PACKAGE_DATA_DIR "/" PACKAGE*/"../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*espace_reclamation = create_espace_reclamation ();
  gtk_widget_show (espace_reclamation);
  bien_saisie = create_bien_saisie ();
  gtk_widget_show (bien_saisie);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);*/
  acceuil = create_acceuil ();
  gtk_widget_show (acceuil);
  treeview1=lookup_widget(acceuil,"treeview1");
  afficher_rec(treeview1);

 
 /* modifier_rec = create_modifier_rec ();
  gtk_widget_show (modifier_rec);
  rechercher = create_rechercher ();
  gtk_widget_show (rechercher);*/

  gtk_main ();
  return 0;
}

